server:
  port: 8080

spring:
  mvc:
    static-path-pattern: /static/**
  
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.comk4qk0lgp4.ap-northeast-2.rds.amazonaws.com:3306/clone?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: admin
    password: 1q2w3e4r
#  security:
#    user:
#      name: admin
#      password: 1q2w3e4r  

mybatis:
  mapper-locations:
  - /mappers/*.xml
  
file:
  path: C:/Users/eastzi/Desktop/spring/workspace/stussy-clone/upload/